[WIP] Reduce CI
Signed-off-by: Hanno Becker <beckphan@amazon.co.uk>

diff --git a/.github/actions/config-variations/action.yml b/.github/actions/config-variations/action.yml
--- a/.github/actions/config-variations/action.yml
+++ b/.github/actions/config-variations/action.yml
@@ -18,35 +18,35 @@ inputs:
 runs:
   using: 'composite'
   steps:
-    - name: "PCT enabled"
-      if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'pct-enabled') }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-DMLD_CONFIG_KEYGEN_PCT -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: true
-        extra_args: "--exclude-example basic_deterministic"
-    - name: "PCT enabled + broken"
-      if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'pct-enabled-broken') }}
-      shell: bash
-      run: |
-        make clean
-        CFLAGS='-Itest -DMLD_CONFIG_FILE=\"break_pct_config.h\"' make func -j4
-        # PCT breakage is done at runtime via MLD_BREAK_PCT
-        make run_func                 # Should be OK
-        MLD_BREAK_PCT=0 make run_func # Should be OK
-        if (MLD_BREAK_PCT=1 make run_func 2>&1 >/dev/null); then
-           echo "PCT failure expected"
-           exit 1
-        else
-           echo "PCT failed as expected"
-        fi
+    # - name: "PCT enabled"
+    #   if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'pct-enabled') }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-DMLD_CONFIG_KEYGEN_PCT -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: true
+    #     extra_args: "--exclude-example basic_deterministic"
+    # - name: "PCT enabled + broken"
+    #   if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'pct-enabled-broken') }}
+    #   shell: bash
+    #   run: |
+    #     make clean
+    #     CFLAGS='-Itest -DMLD_CONFIG_FILE=\"break_pct_config.h\"' make func -j4
+    #     # PCT breakage is done at runtime via MLD_BREAK_PCT
+    #     make run_func                 # Should be OK
+    #     MLD_BREAK_PCT=0 make run_func # Should be OK
+    #     if (MLD_BREAK_PCT=1 make run_func 2>&1 >/dev/null); then
+    #        echo "PCT failure expected"
+    #        exit 1
+    #     else
+    #        echo "PCT failed as expected"
+    #     fi
     - name: "Custom allocation (heap based)"
       if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'custom-alloc-heap') }}
       uses: ./.github/actions/multi-functest
@@ -61,146 +61,146 @@ runs:
         opt: ${{ inputs.opt }}
         extra_env: 'ASAN_OPTIONS=detect_leaks=1'
         examples: false # Some examples use a custom config themselves
-    - name: "Custom zeroization (explicit_bzero)"
-      if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'custom-zeroize') }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_zeroize_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: false # Some examples use a custom config themselves
-    - name: "Custom native capability functions (static ON)"
-      if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'native-cap-ON') }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_native_capability_config_1.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: false # Some examples use a custom config themselves
-    - name: "Custom native capability functions (static OFF)"
-      if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'native-cap-OFF') }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_native_capability_config_0.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: false # Some examples use a custom config themselves
-    - name: "Custom native capability functions (ID_AA64PFR1_EL1 detection)"
-      if: ${{ (inputs.tests == 'all' || contains(inputs.tests, 'native-cap-ID_AA64PFR1_EL1')) && runner.os == 'Linux' && runner.arch == 'ARM64' }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-std=c11 -march=armv8.4-a+sha3 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_native_capability_config_ID_AA64PFR1_EL1.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: false # Some examples use a custom config themselves
-    - name: "Custom native capability functions (CPUID AVX2 detection)"
-      if: ${{ (inputs.tests == 'all' || contains(inputs.tests, 'native-cap-CPUID_AVX2')) && runner.os == 'Linux' && runner.arch == 'X64' }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-std=c11 -mavx2 -mbmi2 -mpopcnt -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_native_capability_config_CPUID_AVX2.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: false # Some examples use a custom config themselves
-    - name: "No ASM"
-      if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'no-asm') }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"no_asm_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: false # Some examples use a custom config themselves
-    - name: "Serial FIPS202 (no batched Keccak)"
-      if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'serial-fips202') }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"serial_fips202_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: false # Some examples use a custom config themselves
-    - name: "Custom randombytes"
-      if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'custom-randombytes') }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_randombytes_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: false # Some examples use a custom config themselves
-    - name: "Custom memcpy"
-      if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'custom-memcpy') }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_memcpy_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: false # Some examples use a custom config themselves
-    - name: "Custom memset"
-      if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'custom-memset') }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_memset_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: false # Some examples use a custom config themselves
-    - name: "Custom stdlib (memcpy + memset)"
-      if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'custom-stdlib') }}
-      uses: ./.github/actions/multi-functest
-      with:
-        gh_token: ${{ inputs.gh_token }}
-        compile_mode: native
-        cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_stdlib_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
-        func: true
-        kat: true
-        acvp: true
-        opt: ${{ inputs.opt }}
-        examples: false # Some examples use a custom config themselves
+    # - name: "Custom zeroization (explicit_bzero)"
+    #   if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'custom-zeroize') }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_zeroize_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: false # Some examples use a custom config themselves
+    # - name: "Custom native capability functions (static ON)"
+    #   if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'native-cap-ON') }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_native_capability_config_1.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: false # Some examples use a custom config themselves
+    # - name: "Custom native capability functions (static OFF)"
+    #   if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'native-cap-OFF') }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_native_capability_config_0.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: false # Some examples use a custom config themselves
+    # - name: "Custom native capability functions (ID_AA64PFR1_EL1 detection)"
+    #   if: ${{ (inputs.tests == 'all' || contains(inputs.tests, 'native-cap-ID_AA64PFR1_EL1')) && runner.os == 'Linux' && runner.arch == 'ARM64' }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-std=c11 -march=armv8.4-a+sha3 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_native_capability_config_ID_AA64PFR1_EL1.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: false # Some examples use a custom config themselves
+    # - name: "Custom native capability functions (CPUID AVX2 detection)"
+    #   if: ${{ (inputs.tests == 'all' || contains(inputs.tests, 'native-cap-CPUID_AVX2')) && runner.os == 'Linux' && runner.arch == 'X64' }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-std=c11 -mavx2 -mbmi2 -mpopcnt -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_native_capability_config_CPUID_AVX2.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: false # Some examples use a custom config themselves
+    # - name: "No ASM"
+    #   if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'no-asm') }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"no_asm_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: false # Some examples use a custom config themselves
+    # - name: "Serial FIPS202 (no batched Keccak)"
+    #   if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'serial-fips202') }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"serial_fips202_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: false # Some examples use a custom config themselves
+    # - name: "Custom randombytes"
+    #   if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'custom-randombytes') }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_randombytes_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: false # Some examples use a custom config themselves
+    # - name: "Custom memcpy"
+    #   if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'custom-memcpy') }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_memcpy_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: false # Some examples use a custom config themselves
+    # - name: "Custom memset"
+    #   if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'custom-memset') }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_memset_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: false # Some examples use a custom config themselves
+    # - name: "Custom stdlib (memcpy + memset)"
+    #   if: ${{ inputs.tests == 'all' || contains(inputs.tests, 'custom-stdlib') }}
+    #   uses: ./.github/actions/multi-functest
+    #   with:
+    #     gh_token: ${{ inputs.gh_token }}
+    #     compile_mode: native
+    #     cflags: "-std=c11 -D_GNU_SOURCE -Itest -DMLD_CONFIG_FILE=\\\\\\\"custom_stdlib_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     ldflags: "-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
+    #     func: true
+    #     kat: true
+    #     acvp: true
+    #     opt: ${{ inputs.opt }}
+    #     examples: false # Some examples use a custom config themselves
